[tool.poetry]
name = "fastapi-rls"
version = "0.0.1"
description = "fastapi sqlalchemy rls integration package"
authors = [
  "DelfinaCare <open-source@delfina.com>"
]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11"
annotated-types = "0.7.0"
anyio = "4.4.0"
fastapi = "0.114.2"
greenlet = "3.1.0"
idna = "3.10"
psycopg2 = "2.9.9"
pydantic = "2.9.1"
pydantic-core = "2.23.3"
sniffio = "1.3.1"
sqlalchemy = "2.0.34"
starlette = "0.38.5"
typing-extensions = "4.12.2"
asyncpg = "^0.29.0"
once-py = "^0.0.6"


[tool.poetry.group.dev.dependencies]
mypy = "^1.11.2"
pre-commit = "^3.8.0"
uvicorn = "^0.30.6"
httpx = "^0.27.2"
pytest = "^8.3.3"
deptry = "^0.20.0"
pytest-asyncio = "^0.24.0"
pytest-xdist = "^3.6.1"
requests = "^2.32.3"
alembic = "^1.13.3"

[project]
name = "fastapi-rls"
version = "0.0.1"
authors = [
  { name = "DelfinaCare", email = "open-source@delfina.com" }
]
description = "fastapi sqlalchemy rls integration package"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/DelfinaCare/fastapi-rls"
Issues = "https://github.com/DelfinaCare/fastapi-rls/issues"
